version: '3.9'

services:
  db:
    image: mysql:8.1
    container_name: gp_mysql
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./server
    container_name: gp_api
    restart: unless-stopped
    env_file:
      - server/.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: gp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: